outputPath: stan
combinedFileName: combined
includes: []
excludes:
  - assets
  - docs
scripts:
  build: rimraf dist && rollup --config rollup.config.ts --configPlugin
    @rollup/plugin-typescript
  docs: typedoc
  knip: knip
  lint: eslint .
  test: vitest --run --coverage
  typecheck: tsc
