outputPath: stan
includes: []
excludes:
  - assets
  - docs
  - package-lock.json
  - '*.local'
scripts:
  build: npm run stan:build
  docs: npm run stan:docs
  knip: npm run knip
  lint: npm run lint
  test: npm run test
  typecheck: npm run typecheck
defaultPatchFile: /stan.patch

