outputPath: stan
combinedFileName: combined
includes: []
excludes:
  - assets
  - docs
scripts:
  build: npm run build
  docs: npm run docs
  knip: npm run knip
  lint: npm run lint
  test: npm run test
  typecheck: npm run typecheck
defaultPatchFile: /stan.patch
